apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vm-user-data
  namespace: default
spec:
  encryptedData:
    userdata: AgABZUyfNvMtDc8tPi4bvjJfYfuX8lhLB+KKRT+kZTUZNH7GaQPt0XKQcqEdhBYstQA+Zgdgw4EZUyyFeTtnfLrTfbNyOjnHy3IcqCiUuS6QoXRD2wvMB85rnzsq9DYrdNEIoZ7ZVvige7je1xZKj/bp7/Ifc7H3PzpCpASAhu87S53bEPEHMVDjyiMkxr4//22uIlq9bvrJ9YO2WYNKYZ+8W7IUqZjN+HDMYAlB3h3mk692Rm8AvbAxYS+TiFlQ0p2kR2LQ0eF6EFeEzcDlcm4pH/8bTuvqmENCKoLt2Vqacz9J2vswgVBL5oR5ODiMrLYATZtRlyM/u/qUegkdw0iLFGCO9UzTO6GXwt2+pzgYgAOi75RF0OaOAUxTOYZUp7yW3CkiLCK6OhwZBQUNqT95gj6hM+M2r3lsEWqMHihX2NSVmmTvn7DwjHZ92xADkWiQgtOCaI8hanTr4XUm1c4RIIBO2IyCJNLBoNcUjr17z52abGrHFrF87j7/mdZU49eYXKMtPYZLqtdxDR9YXMTGD3V1nYAJSdiircdFoSujNQfXMmiAsoD3FIhG67XCvY1nP3AkiiGusJGqDOIQkk9SB1PVCavTrzN0IlnqvzYORVxmh4b/a5RsVNok0ZVPEZt6nVDemNpJ6we7T1m5RL/0M2g190wDFlLPd628IPlrTZtb8VvJJeOfxKCXfR+cIpnqfzLifLFOrWuTJIKJnLe9aA7FObx4YBWLcJUzrHre6+WV16ia4ArPJTVGJF7mQFdeTVkncfhx8ylEcTyi8qkgAAGR4EqQO4Xlgs6j80uIUjbwdKWMVxcm0WSOvbmr/ZUZXcs4YZsuruF+LW5mW+wf/MAry224EeWqmIUn9BgT+LsZxUyXatYx7OAPJfZBILQEjd6tbFyabQ7H+dQRff4nB29/6vTLUbO4mbv+A7jRAMy+7IQGkWbBDjkVCxSiYdTxGNucCjRunZHWW6qOfbNAOSdiuOmXtVXqywiFMOGG0AWekwcc00O2FNtXeTZLAhWy1hTwh0C/5Cy09LR7MH5m2065F9jG8zIrze7FmuuKVSR5DJwAR7Amc9e9++n/XfROyxs3jkPhqZf6VIz7f8akIyXnvpr8r8pyUH5DMyo2ANRrOxFHWBuPXAeXQcdUOGaA5ThUb+6gm6Xz8Yd6gBrG1KdVuzHPwR4oPRN0AY5Han8uQ6LDemQ3tYPTC8IQ3eJ0RwwOh/IYJMeC/9cq3xGE7fGKL/k9FF0xPVz9OLQysDIvjDRUeIq2HVjEj3mSGpwa7AxlC7Duam919fYF9DdUXCql+vhlkKtqa3cObjTHnOG15S4q35U72gGV6NpzPKKll3elSmC22oYKlwHzapCX6lfa3ziWZNSNGVgcESkmUaiXDi0=
  template:
    metadata:
      creationTimestamp: null
      name: vm-user-data
      namespace: default

