apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu
spec:
  running: false
  template:
    spec:
      domain:
        devices:
          disks:
            - name: ubuntu-2204
              disk:
                bus: virtio
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
          - bridge: {}
            model: virtio
            name: default
        resources:
          requests:
            memory: 512M
      networks:
      - name: default
        pod: {}
      volumes:
          - name: ubuntu-2204
            persistentVolumeClaim:
              claimName: ubuntu-22.04
          - name: cloudinitdisk
            cloudInitNoCloud:
              userData: |-
                #cloud-config
                user: ubuntu
                password: ubuntu
                chpasswd: { expire: False }
                ssh_pwauth: True
