apiVersion: v1
kind: Service
metadata:
  name: vm-ssh-lb
  namespace: default
  labels:
    app: vm1
spec:
  type: LoadBalancer
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
  selector:
    app: vm1