apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: eck-storage
  name: eck-storage
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
