apiVersion: v2
name: kubevirt-resources
description: A helm chart to deploy Kubevirt resources into Kubernetes
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: helm-charts
    version: 1.5.3
    repository: oci://registry.tjth.co