helm-charts:
  namespace: cdi
  ingresses:
    - name: cdi-uploadproxy
      commonName: cdi-upload.tjth.co
      secretName: cdi-upload-tjth-co
      port: 8443
      selector:
        cdi.kubevirt.io: cdi-uploadproxy